"""Add admin table

Revision ID: 109978c5866d
Revises: 5cd1b438f03b
Create Date: 2023-05-17 16:29:44.444288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109978c5866d'
down_revision = '5cd1b438f03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_password_hash'), ['password_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_username'))
        batch_op.drop_index(batch_op.f('ix_admin_password_hash'))

    op.drop_table('admin')
    # ### end Alembic commands ###
