"""Add price to Flower

Revision ID: 7946c54be501
Revises: a40da61c4b75
Create Date: 2023-06-13 13:02:28.963696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7946c54be501'
down_revision = 'a40da61c4b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(precision=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flower', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
