"""flowers table

Revision ID: 83aa792acbc1
Revises: 
Create Date: 2023-05-08 10:47:14.049111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83aa792acbc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flower', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flower_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flower', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flower_name'))

    op.drop_table('flower')
    # ### end Alembic commands ###
